/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Posts {
  /**
   * {"xata.link":"users"}
   */
  author: string;
  created_at: Timestamp;
  labels: string[];
  slug: string;
  text: string;
  title: string;
  views: number;
  xata_createdat: Generated<Timestamp>;
  xata_id: Generated<string>;
  xata_updatedat: Generated<Timestamp>;
  xata_version: Generated<number>;
}

export interface Users {
  bio: string;
  email: string;
  name: string;
  xata_createdat: Generated<Timestamp>;
  xata_id: Generated<string>;
  xata_updatedat: Generated<Timestamp>;
  xata_version: Generated<number>;
}

export interface DB {
  posts: Posts;
  users: Users;
}
