CREATE SCHEMA IF NOT EXISTS "public";

CREATE TYPE "public"."feedback_category" AS ENUM (
    'idea',
    'issue',
    'general feedback'
);

CREATE TYPE "public"."feedback_status" AS ENUM (
    'under consideration',
    'planned',
    'in progress',
    'done',
    'declined'
);

CREATE TYPE "public"."subscription_frequency" AS ENUM (
    'month',
    'year'
);

CREATE TYPE "public"."subscription_name" AS ENUM (
    'free',
    'pro',
    'max'
);

CREATE TYPE "public"."user_org_role" AS ENUM (
    'admin',
    'user'
);

CREATE TABLE IF NOT EXISTS "public"."activity_seen" (
    "userId" "text" NOT NULL,
    "itemId" "uuid" NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."admin_invites" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "orgId" "uuid" NOT NULL,
    "token" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."comment" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "content" "text" NOT NULL,
    "authorId" "text" NOT NULL,
    "postId" "uuid" NOT NULL,
    "parentCommentId" "uuid",
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "upvotes" numeric DEFAULT '0'::numeric NOT NULL,
    "embedding" "extensions"."halfvec"(3072)
);

CREATE TABLE IF NOT EXISTS "public"."feedback" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "authorId" "text",
    "orgId" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" "public"."feedback_category",
    "upvotes" numeric DEFAULT '0'::numeric NOT NULL,
    "status" "public"."feedback_status",
    "embedding" "extensions"."halfvec"(3072)
);

CREATE TABLE IF NOT EXISTS "public"."insight_reports" (
    "id" bigint NOT NULL,
    "orgId" "uuid" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."insight_reports" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."insight_reports_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."insights" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "orgId" "uuid" NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "upvotes" numeric DEFAULT '0'::numeric NOT NULL,
    "commentCount" numeric DEFAULT '0'::numeric NOT NULL,
    "status" "public"."feedback_status",
    "ids" "text"[] NOT NULL,
    "priority" numeric DEFAULT '0'::numeric NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" "public"."feedback_category"
);

CREATE TABLE IF NOT EXISTS "public"."org" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "orgSubdomain" "text" NOT NULL,
    "isClaimed" boolean DEFAULT false NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "platformTitle" "text" DEFAULT 'Feedback board'::"text" NOT NULL,
    "platformDescription" "text",
    "logo" "text",
    "orgName" "text",
    "orgUrl" "text"
);

CREATE TABLE IF NOT EXISTS "public"."user" (
    "id" "text" NOT NULL,
    "name" "text",
    "email" "text" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updatedAt" timestamp with time zone DEFAULT "now"() NOT NULL,
    "photoURL" "text"
);

CREATE TABLE IF NOT EXISTS "public"."user_org" (
    "userId" "text" NOT NULL,
    "orgId" "uuid" NOT NULL,
    "role" "public"."user_org_role" DEFAULT 'user'::"public"."user_org_role" NOT NULL,
    CONSTRAINT "user_org_role_check" CHECK ((("role")::"text" = ANY (ARRAY[('admin'::character varying)::"text", ('user'::character varying)::"text"])))
);

CREATE TABLE IF NOT EXISTS "public"."user_upvote" (
    "userId" "text" NOT NULL,
    "contentId" "uuid" NOT NULL,
    "createdAt" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE ONLY "public"."activity_seen"
    ADD CONSTRAINT "activity_seen_pkey" PRIMARY KEY ("userId", "itemId");

ALTER TABLE ONLY "public"."activity_seen"
    ADD CONSTRAINT "activity_seen_userid_itemid_unique" UNIQUE ("userId", "itemId");

ALTER TABLE ONLY "public"."admin_invites"
    ADD CONSTRAINT "admin_invites_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."admin_invites"
    ADD CONSTRAINT "admin_invites_token_key" UNIQUE ("token");

ALTER TABLE ONLY "public"."comment"
    ADD CONSTRAINT "comment_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."feedback"
    ADD CONSTRAINT "feedback_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."insight_reports"
    ADD CONSTRAINT "insight_reports_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."insights"
    ADD CONSTRAINT "insights_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."org"
    ADD CONSTRAINT "org_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."org"
    ADD CONSTRAINT "org_subdomain_key" UNIQUE ("orgSubdomain");

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."user_org"
    ADD CONSTRAINT "user_org_pk" PRIMARY KEY ("userId", "orgId");

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_upvote"
    ADD CONSTRAINT "user_upvote_pkey" PRIMARY KEY ("userId", "contentId");

CREATE INDEX "comment_author_id_index" ON "public"."comment" USING "btree" ("authorId");

CREATE INDEX "comment_embedding_index" ON "public"."comment" USING "hnsw" ("embedding" "extensions"."halfvec_cosine_ops");

CREATE INDEX "comment_parent_comment_id_index" ON "public"."comment" USING "btree" ("parentCommentId");

CREATE INDEX "comment_post_id_index" ON "public"."comment" USING "btree" ("postId");

CREATE INDEX "feedback_embedding_index" ON "public"."feedback" USING "hnsw" ("embedding" "extensions"."halfvec_cosine_ops");

CREATE INDEX "feedback_orgid_idx" ON "public"."feedback" USING "btree" ("orgId");

CREATE INDEX "feedback_status_idx" ON "public"."feedback" USING "btree" ("status");

CREATE INDEX "idx_comment_created_at" ON "public"."comment" USING "btree" ("createdAt");

CREATE INDEX "idx_feedback_created_at" ON "public"."feedback" USING "btree" ("createdAt");

CREATE INDEX "idx_feedback_created_at_upvotes" ON "public"."feedback" USING "btree" ("createdAt", "upvotes");

CREATE INDEX "idx_feedback_createdat_status" ON "public"."feedback" USING "btree" ("createdAt", "status");

CREATE INDEX "idx_feedback_upvotes" ON "public"."feedback" USING "btree" ("upvotes");

CREATE INDEX "insights_org_id_index" ON "public"."insights" USING "btree" ("orgId");

ALTER TABLE ONLY "public"."activity_seen"
    ADD CONSTRAINT "activity_seen_status_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."admin_invites"
    ADD CONSTRAINT "admin_invites_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."comment"
    ADD CONSTRAINT "comment_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id");

ALTER TABLE ONLY "public"."comment"
    ADD CONSTRAINT "comment_parentCommentId_fkey" FOREIGN KEY ("parentCommentId") REFERENCES "public"."comment"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."comment"
    ADD CONSTRAINT "comment_postId_fkey" FOREIGN KEY ("postId") REFERENCES "public"."feedback"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."feedback"
    ADD CONSTRAINT "feedback_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "public"."user"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."feedback"
    ADD CONSTRAINT "feedback_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."insight_reports"
    ADD CONSTRAINT "insight_reports_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."insights"
    ADD CONSTRAINT "insights_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_org"
    ADD CONSTRAINT "user_org_org_id_fkey" FOREIGN KEY ("orgId") REFERENCES "public"."org"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_org"
    ADD CONSTRAINT "user_org_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_upvote"
    ADD CONSTRAINT "user_upvote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE CASCADE;